version: '3'
services:
  #Back-end Spring Boot Application
  ice-app:
    build: ./ice-app
    container_name: ice-app
    #Environment variables for Spring Boot Application.
    environment:
      - H2_DB=icecream
      - H2_USER=sa
      - H2_PASSWORD=secret
    ports:
      - 8080:8080
    #Fron-end Angular Application
  ice-ui:
    build:
      context: .
      dockerfile: ./ice-ui/Dockerfile
    container_name: ice-ui
    ports:
      - 4200:80
    links:
      - ice-app
     
