version: '3'
services:
  #Back-end Spring Boot Application
  ice-app:
    build: ./ice-app
    container_name: ice-app
    #Environment variables for Spring Boot Application.
    environment:
      - DB_SERVER=scrum-postgres
      - H2_DB=icecream
      - H2_USER=sa
      - H2_PASSWORD=secret
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    #Fron-end Angular Application
  ice-ui:
    build: ./ice-ui
    container_name: ice-ui
    ports:
      - 4200:80
    links:
      - ice-app
     
